"""initial schema

Revision ID: e1d0628ce86d
Revises: 
Create Date: 2026-10-05 15:20:14.916798
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import app.database.types  # registers the portable Vector column type


revision: str = 'e1d0628ce86d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


REQUIRED_EXTENSIONS = ("vector", "pg_trgm")

VECTOR_INDEXES = (
    "CREATE INDEX IF NOT EXISTS ix_knowledge_chunks_embedding ON knowledge_chunks "
    "USING hnsw (embedding vector_cosine_ops) WITH (m=16, ef_construction=64)",
    "CREATE INDEX IF NOT EXISTS ix_post_embeddings_hnsw ON post_embeddings "
    "USING hnsw (embedding vector_cosine_ops) WITH (m=16, ef_construction=64)",
)


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # pgvector is required by knowledge_chunks.embedding / post_embeddings;
        # pg_trgm backs fuzzy keyword search.
        for extension in REQUIRED_EXTENSIONS:
            op.execute(f"CREATE EXTENSION IF NOT EXISTS {extension}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops_catalog',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_mr', sa.String(length=120), nullable=True),
    sa.Column('name_hi', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=True),
    sa.Column('season', sa.Enum('kharif', 'rabi', 'zaid', 'perennial', 'any', name='season', native_enum=False, length=48), nullable=False),
    sa.Column('default_area_unit', sa.Enum('acre', 'hectare', 'guntha', 'bigha', 'square_metre', name='area_unit', native_enum=False, length=48), nullable=False),
    sa.Column('disease_model_labels', sa.JSON(), nullable=False),
    sa.Column('typical_yield_per_hectare', sa.Numeric(precision=12, scale=3), nullable=True, comment='Reference figure with the source recorded in data/datasets/README.md; used only as a documented baseline, never as a prediction.'),
    sa.Column('reference_source', sa.String(length=255), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crops_catalog')),
    sa.UniqueConstraint('code', name='uq_crops_catalog_code')
    )
    op.create_index(op.f('ix_crops_catalog_code'), 'crops_catalog', ['code'], unique=False)
    op.create_table('market_crops',
    sa.Column('crop_code', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('provider_crop_name', sa.String(length=160), nullable=False),
    sa.Column('default_unit', sa.String(length=24), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_crops')),
    sa.UniqueConstraint('crop_code', 'source', name='uq_market_crops_crop_code_source')
    )
    op.create_index(op.f('ix_market_crops_crop_code'), 'market_crops', ['crop_code'], unique=False)
    op.create_table('markets',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('name_local', sa.String(length=160), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('source_name', sa.String(length=160), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name=op.f('ck_markets_latitude_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets')),
    sa.UniqueConstraint('code', name='uq_markets_code')
    )
    op.create_index(op.f('ix_markets_code'), 'markets', ['code'], unique=False)
    op.create_index(op.f('ix_markets_district'), 'markets', ['district'], unique=False)
    op.create_index(op.f('ix_markets_state'), 'markets', ['state'], unique=False)
    op.create_table('model_evaluations',
    sa.Column('model_name', sa.String(length=96), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('evaluation_type', sa.String(length=32), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('confusion_matrix', sa.JSON(), nullable=False),
    sa.Column('per_class_metrics', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_evaluations'))
    )
    op.create_index(op.f('ix_model_evaluations_model_name'), 'model_evaluations', ['model_name'], unique=False)
    op.create_table('model_registry_entries',
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('task', sa.String(length=48), nullable=False),
    sa.Column('framework', sa.String(length=48), nullable=False),
    sa.Column('stage', sa.Enum('staging', 'production', 'archived', name='model_stage', native_enum=False, length=48), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('artifact_uri', sa.String(length=512), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('training_data', sa.JSON(), nullable=False),
    sa.Column('evaluation_report', sa.JSON(), nullable=False),
    sa.Column('model_card_url', sa.String(length=512), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_registry_entries')),
    sa.UniqueConstraint('name', 'version', name='uq_model_registry_entries_name_version')
    )
    op.create_index(op.f('ix_model_registry_entries_name'), 'model_registry_entries', ['name'], unique=False)
    op.create_index('ix_model_registry_entries_name_stage', 'model_registry_entries', ['name', 'stage'], unique=False)
    op.create_index(op.f('ix_model_registry_entries_stage'), 'model_registry_entries', ['stage'], unique=False)
    op.create_table('schemes',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=False),
    sa.Column('name_mr', sa.String(length=300), nullable=True),
    sa.Column('name_hi', sa.String(length=300), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_mr', sa.Text(), nullable=True),
    sa.Column('description_hi', sa.Text(), nullable=True),
    sa.Column('benefits_en', sa.Text(), nullable=True),
    sa.Column('benefits_mr', sa.Text(), nullable=True),
    sa.Column('benefits_hi', sa.Text(), nullable=True),
    sa.Column('eligibility_summary_en', sa.Text(), nullable=True),
    sa.Column('eligibility_summary_mr', sa.Text(), nullable=True),
    sa.Column('eligibility_summary_hi', sa.Text(), nullable=True),
    sa.Column('application_process_en', sa.Text(), nullable=True),
    sa.Column('application_process_mr', sa.Text(), nullable=True),
    sa.Column('application_process_hi', sa.Text(), nullable=True),
    sa.Column('documents_required', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('state_codes', sa.JSON(), nullable=False),
    sa.Column('crop_codes', sa.JSON(), nullable=False),
    sa.Column('official_source_name', sa.String(length=200), nullable=False),
    sa.Column('official_source_url', sa.String(length=1024), nullable=False),
    sa.Column('application_url', sa.String(length=1024), nullable=True),
    sa.Column('helpline', sa.String(length=64), nullable=True),
    sa.Column('last_verified_on', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'community_reviewed', 'expert_reviewed', 'official', name='verification_status', native_enum=False, length=48), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(name_en) >= 3', name=op.f('ck_schemes_name_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schemes')),
    sa.UniqueConstraint('slug', name='uq_schemes_slug')
    )
    op.create_index(op.f('ix_schemes_category'), 'schemes', ['category'], unique=False)
    op.create_index(op.f('ix_schemes_slug'), 'schemes', ['slug'], unique=False)
    op.create_index(op.f('ix_schemes_verification_status'), 'schemes', ['verification_status'], unique=False)
    op.create_table('users',
    sa.Column('phone_e164', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('primary_role', sa.Enum('farmer', 'expert', 'moderator', 'admin', name='role', native_enum=False, length=48), nullable=False),
    sa.Column('preferred_language', sa.Enum('en', 'mr', 'hi', name='language', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('pending_verification', 'active', 'suspended', 'disabled', name='user_status', native_enum=False, length=48), nullable=False),
    sa.Column('avatar_media_id', sa.Uuid(), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_media_id'], ['media_assets.id'], name='fk_users_avatar_media_id_media_assets', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_e164'), 'users', ['phone_e164'], unique=True)
    op.create_index(op.f('ix_users_primary_role'), 'users', ['primary_role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('weather_alerts',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_alert_id', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('event', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('headline', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_alerts'))
    )
    op.create_index(op.f('ix_weather_alerts_district'), 'weather_alerts', ['district'], unique=False)
    op.create_index(op.f('ix_weather_alerts_state'), 'weather_alerts', ['state'], unique=False)
    op.create_index('ix_weather_alerts_state_window', 'weather_alerts', ['state', 'valid_from', 'valid_to'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('lat_key', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('lon_key', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temp_min_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_max_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rainfall_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rainfall_probability_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('condition_code', sa.String(length=48), nullable=True),
    sa.Column('condition_text', sa.String(length=160), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_forecasts')),
    sa.UniqueConstraint('lat_key', 'lon_key', 'forecast_for', 'provider', name='uq_weather_forecast_place_time_provider')
    )
    op.create_index('ix_weather_forecasts_place', 'weather_forecasts', ['lat_key', 'lon_key', 'forecast_for'], unique=False)
    op.create_table('weather_observations',
    sa.Column('lat_key', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('lon_key', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('place_label', sa.String(length=200), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feels_like_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rainfall_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wind_speed_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pressure_hpa', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('condition_code', sa.String(length=48), nullable=True),
    sa.Column('condition_text', sa.String(length=160), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_observations')),
    sa.UniqueConstraint('lat_key', 'lon_key', 'observed_at', 'provider', name='uq_weather_obs_place_time_provider')
    )
    op.create_index('ix_weather_observations_place', 'weather_observations', ['lat_key', 'lon_key', 'observed_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(length=24), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('auth_identities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('phone', 'email', name='auth_identity_kind', native_enum=False, length=48), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identities')),
    sa.UniqueConstraint('kind', 'value', name='uq_auth_identities_kind_value')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('background_jobs',
    sa.Column('kind', sa.Enum('disease_detection', 'embed_post', 'embed_document', 'ingest_document', 'notification_fanout', 'weather_alert_scan', 'market_sync', 'crop_reminder_scan', 'model_evaluation', 'embedding_reindex', name='job_kind', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='job_status', native_enum=False, length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_background_jobs_attempts_non_negative')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_background_jobs_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_jobs')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_background_jobs_dedupe_key'))
    )
    op.create_index(op.f('ix_background_jobs_kind'), 'background_jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_background_jobs_requested_by_id'), 'background_jobs', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_index('ix_background_jobs_status_scheduled', 'background_jobs', ['status', 'scheduled_at'], unique=False)
    op.create_table('device_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_device_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_tokens')),
    sa.UniqueConstraint('token', name='uq_device_tokens_token')
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('farmer_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('taluka', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('farming_experience_years', sa.Integer(), nullable=True),
    sa.Column('primary_crops', sa.JSON(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('total_land_area', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_land_unit', sa.Enum('acre', 'hectare', 'guntha', 'bigha', 'square_metre', name='area_unit', native_enum=False, length=48), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('organisation', sa.String(length=160), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('farming_experience_years IS NULL OR (farming_experience_years >= 0 AND farming_experience_years <= 100)', name=op.f('ck_farmer_profiles_farming_experience_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_farmer_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmer_profiles')),
    sa.UniqueConstraint('user_id', name='uq_farmer_profiles_user_id')
    )
    op.create_index(op.f('ix_farmer_profiles_district'), 'farmer_profiles', ['district'], unique=False)
    op.create_index(op.f('ix_farmer_profiles_state'), 'farmer_profiles', ['state'], unique=False)
    op.create_index(op.f('ix_farmer_profiles_user_id'), 'farmer_profiles', ['user_id'], unique=False)
    op.create_table('farms',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('area_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('area_unit', sa.Enum('acre', 'hectare', 'guntha', 'bigha', 'square_metre', name='area_unit', native_enum=False, length=48), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('taluka', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('soil_type', sa.Enum('alluvial', 'black_cotton', 'red', 'laterite', 'sandy', 'clay', 'loamy', 'saline', 'mixed', 'unknown', name='soil_type', native_enum=False, length=48), nullable=False),
    sa.Column('soil_ph', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('irrigation_type', sa.Enum('rainfed', 'canal', 'borewell', 'open_well', 'drip', 'sprinkler', 'tank', 'other', name='irrigation_type', native_enum=False, length=48), nullable=False),
    sa.Column('ownership_type', sa.Enum('owned', 'leased', 'shared', 'government_leased', name='ownership_type', native_enum=False, length=48), nullable=False),
    sa.Column('water_source_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('area_value > 0', name=op.f('ck_farms_area_positive')),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name=op.f('ck_farms_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name=op.f('ck_farms_longitude_range')),
    sa.CheckConstraint('soil_ph IS NULL OR (soil_ph >= 0 AND soil_ph <= 14)', name=op.f('ck_farms_soil_ph_range')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_farms_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farms'))
    )
    op.create_index(op.f('ix_farms_district'), 'farms', ['district'], unique=False)
    op.create_index(op.f('ix_farms_owner_id'), 'farms', ['owner_id'], unique=False)
    op.create_index(op.f('ix_farms_state'), 'farms', ['state'], unique=False)
    op.create_table('follows',
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('followee_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> followee_id', name=op.f('ck_follows_no_self_follow')),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], name=op.f('fk_follows_followee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_follows_follower_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follows')),
    sa.UniqueConstraint('follower_id', 'followee_id', name='uq_follows_follower_id_followee_id')
    )
    op.create_index(op.f('ix_follows_followee_id'), 'follows', ['followee_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_organisation_type', sa.String(length=64), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('last_updated_on', sa.Date(), nullable=True),
    sa.Column('language', sa.Enum('en', 'mr', 'hi', name='language', native_enum=False, length=48), nullable=False),
    sa.Column('doc_type', sa.Enum('article', 'crop_guide', 'disease_info', 'government_info', 'institution_content', 'research_paper', 'faq', 'advisory', name='document_type', native_enum=False, length=48), nullable=False),
    sa.Column('crop_codes', sa.JSON(), nullable=False),
    sa.Column('state_codes', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(length=160), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ingestion_method', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'community_reviewed', 'expert_reviewed', 'official', name='verification_status', native_enum=False, length=48), nullable=False),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexing_status', sa.String(length=16), nullable=False),
    sa.Column('indexing_error', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(title) >= 5', name=op.f('ck_knowledge_documents_title_length')),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_knowledge_documents_verified_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents'))
    )
    op.create_index(op.f('ix_knowledge_documents_doc_type'), 'knowledge_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_indexing_status'), 'knowledge_documents', ['indexing_status'], unique=False)
    op.create_index('ix_knowledge_documents_lang_type', 'knowledge_documents', ['language', 'doc_type'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_verification_status'), 'knowledge_documents', ['verification_status'], unique=False)
    op.create_table('market_prices',
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('crop_code', sa.String(length=48), nullable=False),
    sa.Column('crop_name', sa.String(length=120), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('modal_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('arrivals_tonnes', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=96), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_price IS NULL OR max_price IS NULL OR max_price >= min_price', name=op.f('ck_market_prices_price_range')),
    sa.CheckConstraint('modal_price IS NULL OR modal_price >= 0', name=op.f('ck_market_prices_modal_price_non_negative')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_prices_market_id_markets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_prices')),
    sa.UniqueConstraint('market_id', 'crop_code', 'price_date', 'source', 'is_estimate', name='uq_market_prices_market_crop_date_source_kind')
    )
    op.create_index(op.f('ix_market_prices_crop_code'), 'market_prices', ['crop_code'], unique=False)
    op.create_index('ix_market_prices_date', 'market_prices', ['price_date'], unique=False)
    op.create_index(op.f('ix_market_prices_is_estimate'), 'market_prices', ['is_estimate'], unique=False)
    op.create_index('ix_market_prices_lookup', 'market_prices', ['crop_code', 'market_id', 'price_date'], unique=False)
    op.create_index(op.f('ix_market_prices_market_id'), 'market_prices', ['market_id'], unique=False)
    op.create_index(op.f('ix_market_prices_price_date'), 'market_prices', ['price_date'], unique=False)
    op.create_index(op.f('ix_market_prices_source'), 'market_prices', ['source'], unique=False)
    op.create_table('media_assets',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('public_url', sa.String(length=1024), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_notes', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_media_assets_size_positive')),
    sa.CheckConstraint('width IS NULL OR width > 0', name=op.f('ck_media_assets_width_positive')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_media_assets_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('storage_key', name='uq_media_assets_storage_key')
    )
    op.create_index(op.f('ix_media_assets_checksum_sha256'), 'media_assets', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_media_assets_owner_id'), 'media_assets', ['owner_id'], unique=False)
    op.create_table('model_inference_events',
    sa.Column('model_name', sa.String(length=96), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('input_features', sa.JSON(), nullable=False),
    sa.Column('output_summary', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latency_ms >= 0', name=op.f('ck_model_inference_events_latency_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_model_inference_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_inference_events'))
    )
    op.create_index(op.f('ix_model_inference_events_input_fingerprint'), 'model_inference_events', ['input_fingerprint'], unique=False)
    op.create_index('ix_model_inference_events_model_created', 'model_inference_events', ['model_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_model_inference_events_user_id'), 'model_inference_events', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('weather_alerts', sa.Boolean(), nullable=False),
    sa.Column('market_updates', sa.Boolean(), nullable=False),
    sa.Column('crop_reminders', sa.Boolean(), nullable=False),
    sa.Column('community_activity', sa.Boolean(), nullable=False),
    sa.Column('scheme_updates', sa.Boolean(), nullable=False),
    sa.Column('ai_job_updates', sa.Boolean(), nullable=False),
    sa.Column('digest_only', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('max_per_day', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', name='uq_notification_preferences_user_id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('comment_reply', 'mention', 'post_in_feed', 'weather_alert', 'market_update', 'crop_reminder', 'scheme_update', 'ai_job_complete', 'moderation_action', 'system', name='notification_type', native_enum=False, length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=600), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('deep_link', sa.String(length=512), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('push_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('push_error', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'type', 'subject_type', 'subject_id', name='uq_notifications_dedupe')
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.Enum('register', 'login', 'password_reset', 'phone_verify', name='otp_purpose', native_enum=False, length=48), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('request_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_challenges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_challenges'))
    )
    op.create_index(op.f('ix_otp_challenges_identifier'), 'otp_challenges', ['identifier'], unique=False)
    op.create_index(op.f('ix_otp_challenges_user_id'), 'otp_challenges', ['user_id'], unique=False)
    op.create_table('product_events',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('anonymous_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=24), nullable=False),
    sa.Column('app_version', sa.String(length=24), nullable=True),
    sa.Column('props', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_product_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_events'))
    )
    op.create_index(op.f('ix_product_events_name'), 'product_events', ['name'], unique=False)
    op.create_index('ix_product_events_name_created', 'product_events', ['name', 'created_at'], unique=False)
    op.create_index('ix_product_events_user_created', 'product_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_product_events_user_id'), 'product_events', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('device_label', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('post', 'comment', 'user', name='report_target_type', native_enum=False, length=48), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Enum('spam', 'abuse', 'misinformation', 'off_topic', 'duplicate', 'other', name='report_reason', native_enum=False, length=48), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_review', 'resolved', 'dismissed', name='report_status', native_enum=False, length=48), nullable=False),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_reports_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('reporter_id', 'target_type', 'target_id', name='uq_reports_reporter_target')
    )
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index('ix_reports_status_created', 'reports', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_target_id'), 'reports', ['target_id'], unique=False)
    op.create_table('scheme_eligibility_rules',
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('operator', sa.String(length=16), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('is_hard_requirement', sa.Boolean(), nullable=False),
    sa.Column('note_en', sa.String(length=400), nullable=True),
    sa.Column('source_reference', sa.String(length=400), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operator IN ('<=','<','>=','>','==','!=','in','not_in','contains','is_true','is_false')", name=op.f('ck_scheme_eligibility_rules_operator_supported')),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_scheme_eligibility_rules_scheme_id_schemes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheme_eligibility_rules'))
    )
    op.create_index(op.f('ix_scheme_eligibility_rules_scheme_id'), 'scheme_eligibility_rules', ['scheme_id'], unique=False)
    op.create_table('search_events',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('query', sa.String(length=400), nullable=False),
    sa.Column('mode', sa.Enum('keyword', 'semantic', 'hybrid', name='search_mode', native_enum=False, length=48), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('clicked_target_type', sa.String(length=32), nullable=True),
    sa.Column('clicked_target_id', sa.Uuid(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_events'))
    )
    op.create_index('ix_search_events_user_created', 'search_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_search_events_user_id'), 'search_events', ['user_id'], unique=False)
    op.create_table('user_restrictions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('capability', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_user_restrictions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_restrictions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_restrictions'))
    )
    op.create_index(op.f('ix_user_restrictions_active'), 'user_restrictions', ['active'], unique=False)
    op.create_index(op.f('ix_user_restrictions_user_id'), 'user_restrictions', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'expert', 'moderator', 'admin', name='role', native_enum=False, length=48), nullable=False),
    sa.Column('granted_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_user_roles_granted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_roles_user_id_role')
    )
    op.create_index(op.f('ix_user_roles_role'), 'user_roles', ['role'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('ai_requests',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('disease_detection', 'crop_recommendation', 'yield_prediction', 'price_estimate', 'risk_assessment', 'assistant_chat', 'agent_run', 'embedding', name='ai_request_kind', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='ai_request_status', native_enum=False, length=48), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('input_summary', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=96), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=48), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_ai_requests_latency_non_negative')),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], name=op.f('fk_ai_requests_job_id_background_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_requests_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_requests'))
    )
    op.create_index(op.f('ix_ai_requests_kind'), 'ai_requests', ['kind'], unique=False)
    op.create_index('ix_ai_requests_kind_status', 'ai_requests', ['kind', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_requests_status'), 'ai_requests', ['status'], unique=False)
    op.create_index(op.f('ix_ai_requests_user_id'), 'ai_requests', ['user_id'], unique=False)
    op.create_table('crops',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('crop_code', sa.String(length=48), nullable=False),
    sa.Column('variety', sa.String(length=120), nullable=True),
    sa.Column('season', sa.Enum('kharif', 'rabi', 'zaid', 'perennial', 'any', name='season', native_enum=False, length=48), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('area_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('area_unit', sa.Enum('acre', 'hectare', 'guntha', 'bigha', 'square_metre', name='area_unit', native_enum=False, length=48), nullable=False),
    sa.Column('stage', sa.Enum('planned', 'land_preparation', 'sowing', 'germination', 'vegetative', 'flowering', 'fruiting', 'maturity', 'harvest', 'post_harvest', name='crop_stage', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('active', 'harvested', 'failed', 'planned', name='crop_status', native_enum=False, length=48), nullable=False),
    sa.Column('irrigation_method', sa.Enum('rainfed', 'canal', 'borewell', 'open_well', 'drip', 'sprinkler', 'tank', 'other', name='irrigation_type', native_enum=False, length=48), nullable=True),
    sa.Column('seed_source', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('area_value IS NULL OR area_value > 0', name=op.f('ck_crops_area_positive')),
    sa.CheckConstraint('expected_harvest_date IS NULL OR sowing_date IS NULL OR expected_harvest_date >= sowing_date', name=op.f('ck_crops_harvest_after_sowing')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_crops_farm_id_farms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crops'))
    )
    op.create_index(op.f('ix_crops_crop_code'), 'crops', ['crop_code'], unique=False)
    op.create_index(op.f('ix_crops_farm_id'), 'crops', ['farm_id'], unique=False)
    op.create_index(op.f('ix_crops_stage'), 'crops', ['stage'], unique=False)
    op.create_index(op.f('ix_crops_status'), 'crops', ['status'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('embedding', app.database.types.Vector(), nullable=True),
    sa.Column('embedding_model', sa.String(length=96), nullable=True),
    sa.Column('embedding_version', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_knowledge_chunks_chunk_index_non_negative')),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_knowledge_chunks_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_knowledge_chunks_document_index')
    )
    op.create_index(op.f('ix_knowledge_chunks_content_hash'), 'knowledge_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_table('moderation_cases',
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.Enum('post', 'comment', 'user', name='report_target_type', native_enum=False, length=48), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Enum('spam', 'abuse', 'misinformation', 'off_topic', 'duplicate', 'other', name='report_reason', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_review', 'resolved', 'dismissed', name='report_status', native_enum=False, length=48), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('ai_signals', sa.JSON(), nullable=False),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_moderation_cases_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_moderation_cases_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_moderation_cases_report_id_reports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_moderation_cases_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_cases')),
    sa.UniqueConstraint('report_id', name='uq_moderation_cases_report_id')
    )
    op.create_index(op.f('ix_moderation_cases_author_id'), 'moderation_cases', ['author_id'], unique=False)
    op.create_index(op.f('ix_moderation_cases_status'), 'moderation_cases', ['status'], unique=False)
    op.create_index('ix_moderation_cases_status_created', 'moderation_cases', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_moderation_cases_target_id'), 'moderation_cases', ['target_id'], unique=False)
    op.create_table('soil_tests',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('tested_on', sa.Date(), nullable=False),
    sa.Column('ph', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('nitrogen_kg_per_ha', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('phosphorus_kg_per_ha', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('potassium_kg_per_ha', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('organic_carbon_percent', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('electrical_conductivity', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('lab_name', sa.String(length=160), nullable=True),
    sa.Column('report_media_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nitrogen_kg_per_ha IS NULL OR nitrogen_kg_per_ha >= 0', name=op.f('ck_soil_tests_nitrogen_non_negative')),
    sa.CheckConstraint('ph IS NULL OR (ph >= 0 AND ph <= 14)', name=op.f('ck_soil_tests_soil_test_ph_range')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_soil_tests_farm_id_farms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_media_id'], ['media_assets.id'], name=op.f('fk_soil_tests_report_media_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soil_tests'))
    )
    op.create_index(op.f('ix_soil_tests_farm_id'), 'soil_tests', ['farm_id'], unique=False)
    op.create_table('agent_conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=True),
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('fk_agent_conversations_crop_id_crops'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_agent_conversations_farm_id_farms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_conversations'))
    )
    op.create_index(op.f('ix_agent_conversations_user_id'), 'agent_conversations', ['user_id'], unique=False)
    op.create_table('ai_outputs',
    sa.Column('ai_request_id', sa.Uuid(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence_interpretation', sa.String(length=300), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=96), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('insufficient_evidence', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_ai_outputs_confidence_range')),
    sa.ForeignKeyConstraint(['ai_request_id'], ['ai_requests.id'], name=op.f('fk_ai_outputs_ai_request_id_ai_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_outputs')),
    sa.UniqueConstraint('ai_request_id', name='uq_ai_outputs_ai_request_id')
    )
    op.create_index(op.f('ix_ai_outputs_ai_request_id'), 'ai_outputs', ['ai_request_id'], unique=False)
    op.create_table('crop_events',
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('sowing', 'irrigation', 'fertilizer', 'pesticide', 'weeding', 'harvest', 'observation', 'other', name='crop_event_type', native_enum=False, length=48), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name=op.f('ck_crop_events_cost_non_negative')),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 0', name=op.f('ck_crop_events_quantity_non_negative')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_crop_events_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('fk_crop_events_crop_id_crops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crop_events'))
    )
    op.create_index(op.f('ix_crop_events_crop_id'), 'crop_events', ['crop_id'], unique=False)
    op.create_index(op.f('ix_crop_events_event_date'), 'crop_events', ['event_date'], unique=False)
    op.create_table('moderation_actions',
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('moderator_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('dismiss', 'hide', 'remove', 'warn_author', 'restrict_author', 'note', name='moderation_action_type', native_enum=False, length=48), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('restriction_hours', sa.Integer(), nullable=True),
    sa.Column('notified_author', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['moderation_cases.id'], name=op.f('fk_moderation_actions_case_id_moderation_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name=op.f('fk_moderation_actions_moderator_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_actions'))
    )
    op.create_index(op.f('ix_moderation_actions_case_id'), 'moderation_actions', ['case_id'], unique=False)
    op.create_index(op.f('ix_moderation_actions_moderator_id'), 'moderation_actions', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_moderation_actions_target_id'), 'moderation_actions', ['target_id'], unique=False)
    op.create_table('posts',
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('crop_problem', 'disease', 'pest', 'irrigation', 'soil', 'fertilizer', 'weather', 'market', 'machinery', 'government_scheme', 'farming_technique', 'general', name='post_category', native_enum=False, length=48), nullable=False),
    sa.Column('crop_code', sa.String(length=48), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('farm_id', sa.Uuid(), nullable=True),
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('published', 'under_review', 'hidden', 'removed', name='content_status', native_enum=False, length=48), nullable=False),
    sa.Column('trust_label', sa.Enum('farmer_experience', 'community_supported', 'expert_information', 'official_information', 'ai_prediction', name='trust_label', native_enum=False, length=48), nullable=False),
    sa.Column('reaction_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(body) BETWEEN 10 AND 8000', name=op.f('ck_posts_body_length')),
    sa.CheckConstraint('length(title) BETWEEN 5 AND 200', name=op.f('ck_posts_title_length')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_posts_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('fk_posts_crop_id_crops'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_posts_farm_id_farms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_category'), 'posts', ['category'], unique=False)
    op.create_index('ix_posts_category_created', 'posts', ['category', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_crop_code'), 'posts', ['crop_code'], unique=False)
    op.create_index('ix_posts_crop_state', 'posts', ['crop_code', 'state'], unique=False)
    op.create_index(op.f('ix_posts_district'), 'posts', ['district'], unique=False)
    op.create_index(op.f('ix_posts_state'), 'posts', ['state'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index('ix_posts_status_created', 'posts', ['status', 'created_at'], unique=False)
    op.create_table('predictions',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('ai_request_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('disease_detection', 'crop_recommendation', 'yield_prediction', 'price_estimate', 'risk_assessment', 'assistant_chat', 'agent_run', 'embedding', name='ai_request_kind', native_enum=False, length=48), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('crop_code', sa.String(length=48), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('input_summary', sa.JSON(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('model_name', sa.String(length=96), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 1)', name=op.f('ck_predictions_score_range')),
    sa.ForeignKeyConstraint(['ai_request_id'], ['ai_requests.id'], name=op.f('fk_predictions_ai_request_id_ai_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], name=op.f('fk_predictions_media_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_predictions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index(op.f('ix_predictions_crop_code'), 'predictions', ['crop_code'], unique=False)
    op.create_index(op.f('ix_predictions_kind'), 'predictions', ['kind'], unique=False)
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.create_index('ix_predictions_user_kind_created', 'predictions', ['user_id', 'kind', 'created_at'], unique=False)
    op.create_table('agent_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('tool_output_summary', sa.JSON(), nullable=True),
    sa.Column('tool_error', sa.String(length=300), nullable=True),
    sa.Column('ai_request_id', sa.Uuid(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_request_id'], ['ai_requests.id'], name=op.f('fk_agent_messages_ai_request_id_ai_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], name=op.f('fk_agent_messages_conversation_id_agent_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_messages'))
    )
    op.create_index('ix_agent_messages_conversation', 'agent_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_conversation_id'), 'agent_messages', ['conversation_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('ai_output_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('verdict', sa.Enum('helpful', 'not_helpful', 'incorrect', 'report', name='feedback_verdict', native_enum=False, length=48), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('corrected_label', sa.String(length=160), nullable=True),
    sa.Column('correction_details', sa.Text(), nullable=True),
    sa.Column('consent_to_train', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('used_in_training', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_output_id'], ['ai_outputs.id'], name=op.f('fk_ai_feedback_ai_output_id_ai_outputs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_ai_feedback_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_feedback_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_feedback')),
    sa.UniqueConstraint('ai_output_id', 'user_id', name='uq_ai_feedback_ai_output_id_user_id')
    )
    op.create_index(op.f('ix_ai_feedback_ai_output_id'), 'ai_feedback', ['ai_output_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_user_id'), 'ai_feedback', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('published', 'under_review', 'hidden', 'removed', name='content_status', native_enum=False, length=48), nullable=False),
    sa.Column('trust_label', sa.Enum('farmer_experience', 'community_supported', 'expert_information', 'official_information', 'ai_prediction', name='trust_label', native_enum=False, length=48), nullable=False),
    sa.Column('reaction_count', sa.Integer(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('ai_output_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(body) BETWEEN 1 AND 4000', name=op.f('ck_comments_body_length')),
    sa.ForeignKeyConstraint(['ai_output_id'], ['ai_outputs.id'], name=op.f('fk_comments_ai_output_id_ai_outputs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('fk_comments_parent_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comments_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_index('ix_comments_post_created', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_table('post_embeddings',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', app.database.types.Vector(), nullable=False),
    sa.Column('embedding_model', sa.String(length=96), nullable=False),
    sa.Column('embedding_version', sa.String(length=32), nullable=False),
    sa.Column('source_text_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_embeddings_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_embeddings')),
    sa.UniqueConstraint('post_id', name='uq_post_embeddings_post_id')
    )
    op.create_index(op.f('ix_post_embeddings_post_id'), 'post_embeddings', ['post_id'], unique=False)
    op.create_table('post_media',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], name=op.f('fk_post_media_media_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_media_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_media')),
    sa.UniqueConstraint('post_id', 'media_id', name='uq_post_media_post_id_media_id')
    )
    op.create_index(op.f('ix_post_media_post_id'), 'post_media', ['post_id'], unique=False)
    op.create_table('saved_posts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('collection', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_saved_posts_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_posts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_posts')),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_saved_posts_user_id_post_id')
    )
    op.create_index(op.f('ix_saved_posts_post_id'), 'saved_posts', ['post_id'], unique=False)
    op.create_index(op.f('ix_saved_posts_user_id'), 'saved_posts', ['user_id'], unique=False)
    op.create_table('reactions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('comment_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('support', 'helpful', 'insightful', name='reaction_kind', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(post_id IS NOT NULL AND comment_id IS NULL) OR (post_id IS NULL AND comment_id IS NOT NULL)', name=op.f('ck_reactions_exactly_one_target')),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_reactions_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_reactions_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reactions')),
    sa.UniqueConstraint('user_id', 'post_id', 'comment_id', name='uq_reactions_user_target')
    )
    op.create_index(op.f('ix_reactions_comment_id'), 'reactions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_reactions_post_id'), 'reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_reactions_user_id'), 'reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


    _create_vector_indexes()

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactions_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_post_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_comment_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_saved_posts_user_id'), table_name='saved_posts')
    op.drop_index(op.f('ix_saved_posts_post_id'), table_name='saved_posts')
    op.drop_table('saved_posts')
    op.drop_index(op.f('ix_post_media_post_id'), table_name='post_media')
    op.drop_table('post_media')
    op.drop_index(op.f('ix_post_embeddings_post_id'), table_name='post_embeddings')
    op.drop_table('post_embeddings')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index('ix_comments_post_created', table_name='comments')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_ai_feedback_user_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_ai_output_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_agent_messages_conversation_id'), table_name='agent_messages')
    op.drop_index('ix_agent_messages_conversation', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('ix_predictions_user_kind_created', table_name='predictions')
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_kind'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_crop_code'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_posts_status_created', table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_state'), table_name='posts')
    op.drop_index(op.f('ix_posts_district'), table_name='posts')
    op.drop_index('ix_posts_crop_state', table_name='posts')
    op.drop_index(op.f('ix_posts_crop_code'), table_name='posts')
    op.drop_index('ix_posts_category_created', table_name='posts')
    op.drop_index(op.f('ix_posts_category'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_moderation_actions_target_id'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_moderator_id'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_case_id'), table_name='moderation_actions')
    op.drop_table('moderation_actions')
    op.drop_index(op.f('ix_crop_events_event_date'), table_name='crop_events')
    op.drop_index(op.f('ix_crop_events_crop_id'), table_name='crop_events')
    op.drop_table('crop_events')
    op.drop_index(op.f('ix_ai_outputs_ai_request_id'), table_name='ai_outputs')
    op.drop_table('ai_outputs')
    op.drop_index(op.f('ix_agent_conversations_user_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_index(op.f('ix_soil_tests_farm_id'), table_name='soil_tests')
    op.drop_table('soil_tests')
    op.drop_index(op.f('ix_moderation_cases_target_id'), table_name='moderation_cases')
    op.drop_index('ix_moderation_cases_status_created', table_name='moderation_cases')
    op.drop_index(op.f('ix_moderation_cases_status'), table_name='moderation_cases')
    op.drop_index(op.f('ix_moderation_cases_author_id'), table_name='moderation_cases')
    op.drop_table('moderation_cases')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_content_hash'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_crops_status'), table_name='crops')
    op.drop_index(op.f('ix_crops_stage'), table_name='crops')
    op.drop_index(op.f('ix_crops_farm_id'), table_name='crops')
    op.drop_index(op.f('ix_crops_crop_code'), table_name='crops')
    op.drop_table('crops')
    op.drop_index(op.f('ix_ai_requests_user_id'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_status'), table_name='ai_requests')
    op.drop_index('ix_ai_requests_kind_status', table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_kind'), table_name='ai_requests')
    op.drop_table('ai_requests')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_restrictions_user_id'), table_name='user_restrictions')
    op.drop_index(op.f('ix_user_restrictions_active'), table_name='user_restrictions')
    op.drop_table('user_restrictions')
    op.drop_index(op.f('ix_search_events_user_id'), table_name='search_events')
    op.drop_index('ix_search_events_user_created', table_name='search_events')
    op.drop_table('search_events')
    op.drop_index(op.f('ix_scheme_eligibility_rules_scheme_id'), table_name='scheme_eligibility_rules')
    op.drop_table('scheme_eligibility_rules')
    op.drop_index(op.f('ix_reports_target_id'), table_name='reports')
    op.drop_index('ix_reports_status_created', table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_product_events_user_id'), table_name='product_events')
    op.drop_index('ix_product_events_user_created', table_name='product_events')
    op.drop_index('ix_product_events_name_created', table_name='product_events')
    op.drop_index(op.f('ix_product_events_name'), table_name='product_events')
    op.drop_table('product_events')
    op.drop_index(op.f('ix_otp_challenges_user_id'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_identifier'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_model_inference_events_user_id'), table_name='model_inference_events')
    op.drop_index('ix_model_inference_events_model_created', table_name='model_inference_events')
    op.drop_index(op.f('ix_model_inference_events_input_fingerprint'), table_name='model_inference_events')
    op.drop_table('model_inference_events')
    op.drop_index(op.f('ix_media_assets_owner_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_checksum_sha256'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_market_prices_source'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_price_date'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_market_id'), table_name='market_prices')
    op.drop_index('ix_market_prices_lookup', table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_is_estimate'), table_name='market_prices')
    op.drop_index('ix_market_prices_date', table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_crop_code'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_knowledge_documents_verification_status'), table_name='knowledge_documents')
    op.drop_index('ix_knowledge_documents_lang_type', table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_indexing_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_doc_type'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_followee_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_farms_state'), table_name='farms')
    op.drop_index(op.f('ix_farms_owner_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_district'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_farmer_profiles_user_id'), table_name='farmer_profiles')
    op.drop_index(op.f('ix_farmer_profiles_state'), table_name='farmer_profiles')
    op.drop_index(op.f('ix_farmer_profiles_district'), table_name='farmer_profiles')
    op.drop_table('farmer_profiles')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index('ix_background_jobs_status_scheduled', table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_requested_by_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_kind'), table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_weather_observations_place', table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index('ix_weather_forecasts_place', table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index('ix_weather_alerts_state_window', table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_state'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_district'), table_name='weather_alerts')
    op.drop_table('weather_alerts')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_primary_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_e164'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schemes_verification_status'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_slug'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_category'), table_name='schemes')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_model_registry_entries_stage'), table_name='model_registry_entries')
    op.drop_index('ix_model_registry_entries_name_stage', table_name='model_registry_entries')
    op.drop_index(op.f('ix_model_registry_entries_name'), table_name='model_registry_entries')
    op.drop_table('model_registry_entries')
    op.drop_index(op.f('ix_model_evaluations_model_name'), table_name='model_evaluations')
    op.drop_table('model_evaluations')
    op.drop_index(op.f('ix_markets_state'), table_name='markets')
    op.drop_index(op.f('ix_markets_district'), table_name='markets')
    op.drop_index(op.f('ix_markets_code'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_market_crops_crop_code'), table_name='market_crops')
    op.drop_table('market_crops')
    op.drop_index(op.f('ix_crops_catalog_code'), table_name='crops_catalog')
    op.drop_table('crops_catalog')
    # ### end Alembic commands ###


def _create_vector_indexes() -> None:
    """HNSW indexes for cosine similarity search (pgvector only).

    Expression indexes on an extension type are kept out of the autogenerated
    section; the deployment runbook re-runs them after large ingests.
    """
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    for statement in VECTOR_INDEXES:
        op.execute(statement)
