"""Shared response contracts enforcing the data-provenance rules.

Nothing in the platform may return agricultural, market, weather or model data
without declaring which of the three data classes it belongs to:

  * observed/official  → provider + source + retrieved_at (+ is_demo)
  * model output       → model_name + model_version + confidence + disclaimer
  * user content       → trust_label (farmer experience / expert / official / AI)

Keeping this in one module means the Flutter client can rely on the fields
existing, and makes the "don't fabricate data" rule testable.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

DEMO_LABEL = "DEMO DATA — generated by the local development provider, not live data."

AI_DISCLAIMER = (
    "AI-assisted result — not a confirmed diagnosis or a guarantee. "
    "For consequential decisions consult a qualified agricultural professional."
)


class TrustLabel(StrEnum):
    FARMER_EXPERIENCE = "farmer_experience"
    COMMUNITY_SUPPORTED = "community_supported"
    EXPERT_INFORMATION = "expert_information"
    OFFICIAL_INFORMATION = "official_information"
    AI_PREDICTION = "ai_prediction"


class DataClass(StrEnum):
    OBSERVED = "observed"
    MODEL_OUTPUT = "model_output"
    USER_CONTENT = "user_content"
    DERIVED = "derived"  # deterministic rules over other data (e.g. scheme eligibility)


class ApiModel(BaseModel):
    model_config = ConfigDict(from_attributes=True, populate_by_name=True, use_enum_values=True)


class DataSourceMixin(BaseModel):
    """Marks externally-sourced data and its provenance."""

    provider: str = Field(description="Active provider name, e.g. 'mock', 'openweathermap'")
    source: str = Field(description="Human readable source label")
    is_demo: bool = Field(
        default=False,
        description="True when produced by a local/demo provider. Demo data is never mixed with live data.",
    )
    retrieved_at: datetime | None = Field(
        default=None, description="When the upstream data was fetched (not when the row was stored)"
    )
    demo_notice: str | None = Field(
        default=None, description="Populated with an explicit notice whenever is_demo is true"
    )

    def mark_demo(self) -> DataSourceMixin:
        if self.is_demo and not self.demo_notice:
            self.demo_notice = DEMO_LABEL
        return self


class ModelOutputMixin(BaseModel):
    """Marks model-produced values so clients can never present them as facts."""

    model_name: str
    model_version: str
    data_class: Literal["model_output"] = "model_output"
    confidence: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description=(
            "Model score. Interpreted as a probability only when the model card states "
            "the output was calibrated; otherwise it is a relative score."
        ),
    )
    confidence_interpretation: str | None = Field(
        default=None,
        description="Explicit statement of what `confidence` means for this model, incl. calibration status",
    )
    disclaimer: str = AI_DISCLAIMER
    limitations: list[str] = Field(default_factory=list)
    generated_at: datetime | None = None


class TrustLabelMixin(BaseModel):
    trust_label: TrustLabel = TrustLabel.FARMER_EXPERIENCE
    data_class: Literal["user_content"] = "user_content"


class EvidenceItem(BaseModel):
    """A citation. Only ever constructed from rows actually retrieved."""

    kind: Literal[
        "knowledge_chunk",
        "community_post",
        "scheme",
        "market_price",
        "weather",
        "model_card",
        "profile",
    ]
    ref_id: str
    title: str
    source_name: str | None = None
    source_url: str | None = None
    snippet: str | None = None
    score: float | None = None
    published_at: datetime | None = None
    verification_status: str | None = None


class PaginatedResponse(BaseModel):
    items: list[Any]
    page: int
    page_size: int
    total: int
    total_pages: int
    has_next: bool
